package mx.ipn.escom.cdt.besp.modelo;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

/**
 * ColoniaId generated by hbm2java
 */
@Embeddable
public class ProyectoEstructuraId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6401872278691577906L;
	@Column(name = "id_estructura", nullable = false)
	private Integer idEstructura = null;
	@Column(name = "id_proyecto", nullable = false)
	private Integer idProyecto = null;

	public ProyectoEstructuraId() {
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsBuilder.reflectionEquals(this, obj, "");
	}

	@Override
	public String toString() {
		final ReflectionToStringBuilder reflectionToStringBuilder = new ReflectionToStringBuilder(
				this);
		reflectionToStringBuilder.setExcludeFieldNames(new String[] {});
		return reflectionToStringBuilder.toString();
	}

	public Integer getIdProyecto() {
		return this.idProyecto;
	}

	public Integer getIdEstructura() {
		return idEstructura;
	}

	public void setIdEstructura(Integer idEstructura) {
		this.idEstructura = idEstructura;
	}

	public void setIdProyecto(Integer idProyecto) {
		this.idProyecto = idProyecto;
	}

}